name: hydra_engine
description: Multi-protocol network logon audit and authentication resilience tester for Dart & Flutter. Inspired by THC-Hydra.
version: 2.0.0
homepage: https://github.com/AbdoFawzi777/redops-hub/tree/main/packages/hydra_engine

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  crypto: ^3.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

